targets:
  $default:
    builders:
      json_serializable|json_serializable:
        options:
          super-parameters: true
          enhanced-enums: true
      freezed|freezed:
        options:
          super-parameters: true
          enhanced-enums: true
      auto_route|auto_route:
        options:
          super-parameters: true
          enhanced-enums: true